### ISSUE TITLE
vendor-prefixed `visibilitychange` event listener is called the second time in newer browsers

### ISSUE THREAD

**Issue by isocroft** [shawnmclean/Idle.js#30]
In the code for **Idle.js**, There are several vendor-prefixed events setup on the same listener for the _visibilitychange_ event. This makes it fire twice in (newer) browsers that support both the older vendor-prefixed events and the newer unprefixed events. I have corrected this in my personal build of **Idle.js** and would have made a pull request but i don't know how to write *coffeescript* (which is the source language of choice for **Idle.js** ). However, here's my code snippet to remedy this in plain JavaScript

```js
        if(typeof document.addEventListener === 'function'){
          
            if('hidden' in document &&
              !('webkitHidden' in document
                  || 'oHidden' in document
                    || 'mozHidden' in document
                        || 'msHidden' in document)){
                         document.addEventListener("visibilitychange", this.listener, false);
            }else{
                        document.addEventListener("webkitvisibilitychange", this.listener, false);
                        document.addEventListener("msvisibilitychange", this.listener, false);
            }
        }
        .
        .
        .
        if(typeof document.removeEventListener === 'function'){
            if('hidden' in document &&
                  !('webkitHidden' in document
                      || 'oHidden' in document
                        || 'mozHidden' in document
                            || 'msHidden' in document)){
                        document.removeEventListener("visibilitychange", this.listener);
            }else{
                       document.removeEventListener("webkitvisibilitychange", this.listener);
                       document.removeEventListener("msvisibilitychange", this.listener);
           }
        }
```

**Comment by pboisso** [comment]
I'd like to get this fix too.  Did you just added this code snipet to the Idle.js file or was this a replacement for some code already in there?  If the later, which lines did you replace with your new code?  Thanks.

**Comment by isocroft** [comment]
Seems this issue is quite old and also resolved. I'm closing out

**Comment by pboisso** [comment]
I don't think it is resolved.  I had to implement the fix suggested here to make it call 'visibilitychange' event only once here too.

**Comment by Joebayld** [comment]
Can confirm this is not resolved. The event is called twice on the latest Chrome.

**Comment by hakkikonu** [comment]
> Can confirm this is not resolved. The event is called twice on the latest Chrome.

Yes. I have same issue with   visibilitychange event
